config/routes.rb
Rails.application.routes.draw do
  get 'test/principal'

  get 'test/contact'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: "welcome#principal"

  get '/contact/:pepito/:apellido', to: "welcome#contact", as: "contactanos"
  # resources 'welcome'
  # get '/contact/:pepito',  to: "welcome#contact"
  resources :posts
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/post.rb
class Post < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
def index
    @posts = User.all #aqui se esta guardando los registros de la tasbla User
end
end

app/controllers/test_controller.rb
class TestController < ApplicationController
  def principal
  end

  def contact
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
    def principal
        @str = "Hola Mundo"
    end
    def contact
        @name = params["pepito"]
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/test_helper.rb
module TestHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Intagram</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/posts/index.html.erb
    <% @posts.each {|post| %>
    <div> <%= post.comments %> </div>
    <div> <%= post.likes %> </div>
   <% } %>

app/views/welcome/contact.html.erb
<h1><%= @name %></h1>

app/views/welcome/principal.html.erb
<a href=<%= contactanos_path('perez', 'maria') %>>ir a contact view</a>
<% @str = "Hola Leonel" %>

<h1><%= @str %></h1>